# Generated by Django 3.2.18 on 2023-06-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
