# Generated by Django 3.2.18 on 2023-04-26 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_rename_categoria_categorias'),
        ('productos', '0002_rename_categoria_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.categorias'),
        ),
        migrations.DeleteModel(
            name='Categorias',
        ),
    ]
