# Generated by Django 3.2.18 on 2023-06-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='can_sol',
            field=models.IntegerField(default=0),
        ),
    ]
