# Generated by Django 3.2.18 on 2023-06-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0002_insumos_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumos',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
