# Generated by Django 3.2.18 on 2023-06-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0003_alter_insumos_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumos',
            name='can_sol',
            field=models.IntegerField(default=0),
        ),
    ]
