# Generated by Django 3.2.18 on 2023-05-27 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='producto',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='productos',
            field=models.ManyToManyField(to='productos.Producto'),
        ),
    ]
