# Generated by Django 3.2.18 on 2023-05-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_auto_20230527_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='cantidad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='precion',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
