# Generated by Django 3.2.18 on 2023-05-27 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_auto_20230527_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizacion',
            old_name='precion',
            new_name='precio',
        ),
    ]
