# Generated by Django 3.2.18 on 2023-06-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0006_auto_20230527_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecotizacion',
            name='descuento',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='detallecotizacion',
            name='total_coti',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
