# Generated by Django 3.2.18 on 2023-04-27 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_rename_categoria_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='categorias',
            name='material',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
