# Generated by Django 3.2.18 on 2023-06-14 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orden_trabajo', '0002_ordentrabajo_estado_posible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='estado_posible',
        ),
    ]
