# Generated by Django 3.2.18 on 2023-06-15 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_rename_total_compra_detalle_orden_venta_total_venta'),
        ('orden_trabajo', '0003_remove_ordentrabajo_estado_posible'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(default=1234, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='ventas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.ventas'),
        ),
    ]
