# Generated by Django 3.2.18 on 2023-05-29 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_compras_detalle_orden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_orden',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='detalle_orden',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Compras',
        ),
        migrations.DeleteModel(
            name='Detalle_orden',
        ),
    ]
