# Generated by Django 3.2.18 on 2023-06-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_auto_20230529_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedores',
            name='apellido',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedores',
            name='correo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedores',
            name='telefono',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='direccion',
            field=models.CharField(max_length=20),
        ),
    ]
