# Generated by Django 3.2.18 on 2023-06-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_compra', '0002_auto_20230603_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleordencompra',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
