# Generated by Django 3.2.18 on 2023-06-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_compra', '0003_detalleordencompra_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleordencompra',
            name='total_compra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
