# Generated by Django 3.2.18 on 2023-06-12 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_compra', '0005_alter_detalleordencompra_total_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleordencompra',
            name='descuento',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
    ]
