# Generated by Django 3.2.18 on 2023-06-02 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_ventas_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
    ]
