# Generated by Django 3.2.18 on 2023-06-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_precio'),
        ('ventas', '0003_alter_ventas_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle_orden_venta',
            old_name='descuento_detalle',
            new_name='descuento',
        ),
        migrations.RenameField(
            model_name='detalle_orden_venta',
            old_name='sub_total_detalle',
            new_name='total_venta',
        ),
        migrations.RemoveField(
            model_name='detalle_orden_venta',
            name='total_detalle',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='sub_total',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='total',
        ),
        migrations.AddField(
            model_name='ventas',
            name='productos',
            field=models.ManyToManyField(to='productos.Producto'),
        ),
    ]
