# Generated by Django 3.2.18 on 2023-06-12 22:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_auto_20230612_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
