# Generated by Django 3.2.18 on 2023-06-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_ventas_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_orden_venta',
            name='total_venta',
        ),
        migrations.AddField(
            model_name='detalle_orden_venta',
            name='total_compra',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='detalle_orden_venta',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detalle_orden_venta',
            name='descuento',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='detalle_orden_venta',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
