# Generated by Django 3.2.18 on 2023-06-12 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_auto_20230612_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle_orden_venta',
            old_name='total_compra',
            new_name='total_venta',
        ),
    ]
